color0 #141315
color1 #ffb4ab
color2 #c6c4dc
color3 #c8c5d0
color4 #debecd
color5 #c6c4dc
color6 #c8c5d0
color7 #e5e1e3
color8 #929097
color9 #ffb4ab
color10 #c6c4dc
color11 #c8c5d0
color12 #debecd
color13 #c6c4dc
color14 #c8c5d0
color15 #e5e1e3

cursor                #e5e1e3
cursor_text_color     #141315
background            #141315
foreground            #e5e1e3
selection_foreground  #c8c5cd
selection_background  #47464c
active_border_color   #c6c4dc
inactive_border_color #47464c
url_color             #c6c4dc

active_tab_foreground   #2f2f41
active_tab_background   #c6c4dc
inactive_tab_foreground #c8c5cd
inactive_tab_background #47464c
cursor_trail_color      #c8c5cd
