# Source Files
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/startup.conf
source = $HOME/.config/hypr/inputs.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/windowrules.conf
source = $HOME/.config/hypr/animations.conf
source = $HOME/.config/hypr/themes/theme.conf
source = $HOME/.config/hypr/workspaces.conf

#Plugin For Overview
plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(000000)
        workspace_method = center current
	skip_empty = true
    }
}

# Layouts
# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    #pseudotile = yes
    preserve_split = yes
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = master
}


# Misc
# See https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    vrr = 0                      # 0=OFF 1=ON 2=FULLSCREEN ONLY
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    anr_missed_pings = 5
    allow_session_lock_restore = true
}

xwayland {
    force_zero_scaling = true
}

general {
    snap {                       # snapping for floating windows
        enabled = true
    }
}

source = /home/tokit/.config/hypr/noctalia/noctalia-colors.conf

