# ==========================================
# Workspace to Monitor Routing
# ==========================================

# Bind Workspaces 1-5 to Main Monitor (HDMI-A-1)
workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1

# Bind Workspaces 6-10 to Secondary Monitor (HDMI-A-2)
workspace = 6, monitor:HDMI-A-2, default:true
workspace = 7, monitor:HDMI-A-2
workspace = 8, monitor:HDMI-A-2
workspace = 9, monitor:HDMI-A-2
workspace = 10, monitor:HDMI-A-2

# Assign Helium to workspace 2
windowrule = match:class ^(helium)$, workspace 1

# Assign Nautilus to workspace 2
windowrule = match:class ^(org.gnome.Nautilus)$, workspace 2

# Assign Discord to workspace 6 silently
windowrule = match:class ^(discord)$, workspace 6 silent

# Assign Spotify to workspace 7 silently
windowrule = match:class ^(Spotify)$, workspace 7 silent
